export const getGithubWorkflow = (): string => [
  'name: Astro Doctor',
  '',
  'on:',
  '  pull_request:',
  '    types: [opened, synchronize, reopened, ready_for_review]',
  '',
  'permissions:',
  '  contents: read',
  '  pull-requests: write',
  '',
  'concurrency:',
  '  group: astro-doctor-${{ github.event.pull_request.number || github.ref }}',
  '  cancel-in-progress: true',
  '',
  'jobs:',
  '  astro-doctor:',
  '    runs-on: ubuntu-latest',
  '    steps:',
  '      - uses: actions/checkout@v7',
  '        with:',
  '          fetch-depth: 0',
  '      - uses: santi020k/astro-doctor@v1',
  '        with:',
  '          fail-on: \'error\'',
  ''
].join('\n')
