version: "0.2"
language: en
words:
  - astro
  - astrojs
  - attw
  - arethetypeswrong
  - catppuccin
  - changeset
  - changesets
  - cowork
  - cspell
  - commitizen
  - commitlint
  - eslint
  - gitignore
  - jsonc
  - knip
  - lint-staged
  - linter
  - llms
  - llmstxt
  - lspconfig
  - monorepo
  - nvim
  - packagemanager
  - santi
  - santi020k
  - shiki
  - turbo
  - turborepo
  - tsconfig
  - vitest
  - vsce
  - vscodeignore
  - vsix
  - vscode
  - webview
  - workspaces
  - quiescent
  - nonce
  - activitybar
  - languageclient
  - languageserver
  - textdocument
  - evenodd
  - linecap
  - linejoin
  - testnonce
  - mynonce
  - uniquenonce
  - confbox
  - esbuild
  - jiti
  - Contentful
  - WCAG
  - frontmatter
  - OVSX
  - ACMR
  - lockfiles
ignorePaths:
  - node_modules
  - dist
  - coverage
  - .turbo
  - .git
  - .changeset
  - pnpm-lock.yaml
  - "*.log"
  - "**/*.test.ts.snap"
  - .vscode
