export const DEFAULT_DIAGNOSTIC_LINE_NUMBER = 1
export const DEFAULT_DIAGNOSTIC_COLUMN_NUMBER = 1
export const MINIMUM_THRESHOLD_SCORE = 0
export const MAXIMUM_THRESHOLD_SCORE = 100
export const CI_THRESHOLD_SCORE = 90
export const DISABLED_THRESHOLD_SCORE = -1
