export const HTTP_NOT_FOUND_STATUS = 404;
export const HTTP_SERVER_ERROR_MIN_STATUS = 500;
export const HTTP_TOO_MANY_REQUESTS_STATUS = 429;
export const PUBLISH_VERIFY_INTERVAL_MS = 2_000;
export const PUBLISH_VERIFY_MAX_ATTEMPTS = 150;
